import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/main-page/main-header";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${roboto_mono.variable}`}>
      <body className="font-sans">
        <main>
          <MainHeader />
          {children}
        </main>
      </body>
    </html>
  );
}
